name: Build LuaLib

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@master
      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 11.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install node_modules
        run: |
          npm install -g roblox-ts@next
          npm install
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
        
      - name: Generate Lua Bundle
        run: |
          rbxtsc -r luaproject.json
          
      - name: Copy files to LuaLib branch
        run: |
          cd ..
          
          git clone --depth=50 --branch=lualib https://vorlias:${{secrets.git_token}}@github.com/roblox-aurora/rbx-net.git lualib
          rm -rf lualib/*.lua
          cp -r rbx-net/out/* lualib
          
          mkdir -p lualib/vendor
          cp -r rbx-net/include/* lualib/vendor
          
          find lualib -name '*.d.ts' -delete
          
          rm -rf lualib/Test
          
          git add -A
          if ! git diff-index --quiet HEAD --; then
            echo "Lua Build changed!"
            if [ "$GITHUB_EVENT_NAME" == "push" ]; then
              git commit -m "Updated via push"
            else
              git commit -m "Updated via other method"
            fi
            
            git push https://vorlias:${{secrets.git_token}}@github.com/roblox-aurora/rbx-net.git HEAD:lualib
          fi

