name: Deploy @next
on:
  push:
    branches: 
      - master

jobs:
  deploy:
    if: github.repository == 'roblox-aurora/rbx-net' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install node_modules
        run: |
          npm install -g roblox-ts@next
          npm install
      
      - name: Build
        run: rbxtsc
      
      - name: Deploy
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git checkout origin/master tests/package.json
          git checkout origin/master tests/package-lock.json
          npm version prerelease --preid="commit-$(git log --format="%H" -n 1 | head -c 7)" # hack!
          npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          
